<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseAppHost>false</UseAppHost>
    <NuGetAudit>false</NuGetAudit>
    <AssetStudioDir>$(MSBuildThisFileDirectory)../../bin/assetstudio/AssetStudioModCLI_net9_portable</AssetStudioDir>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="$(AssetStudioDir)/*.dll" Exclude="$(AssetStudioDir)/AssetStudioModCLI.dll" />
    <Compile Include="../../bridge/SharedResourceReaders.cs" Link="SharedResourceReaders.cs" />
  </ItemGroup>
</Project>
